apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
{{ include "proxysql.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxysql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "proxysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsNonRoot: true
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash","-c"]
          args: ["envsubst < /etc/proxysql-template.cnf > /var/lib/proxysql/proxysql.cnf && proxysql -f -c /var/lib/proxysql/proxysql.cnf -D /var/lib/proxysql"]
          env:
          - name: ADMIN_PASSWORD
            value: cool
          ports:
            - name: proxysql
              containerPort: 6033
              protocol: TCP
            - name: http-port
              containerPort: 6080
              protocol: TCP
            - name: rest-api
              containerPort: 6070
              protocol: TCP
            - name: admin
              containerPort: 6032
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /usr/local/bin/probe-proxysql.bash
              subPath: probe-proxysql.bash
            - name: {{ .Release.Name }}-config
              mountPath: /usr/local/bin/cleanup-digest.bash
              subPath: cleanup-digest.bash
            - name: {{ .Release.Name }}-config
              mountPath: /etc/proxysql-template.cnf
              subPath: proxysql.cnf
            - mountPath: "/var/lib/proxysql/creds"
              name: credentials
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            exec:
              command: ["/bin/bash","/usr/local/bin/probe-proxysql.bash"]
          readinessProbe:
            exec:
              command: ["/bin/bash","/usr/local/bin/probe-proxysql.bash"]
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ .Release.Name }}-proxysqlcm
            defaultMode: 0755
        - name: credentials
          secret:
            secretName: proxysql-secret
